In [30]:
# Dependencies
import pandas as pd
import pymongo

In [31]:
Country_ESG_df = pd.read_csv('Master Country Environment ESG ratings 8 10 21.csv')

In [32]:
Country_ESG_df.head()

,Country,EPI 2000,EPI 2002,EPI 2004,EPI 2006,EPI 2008,EPI 2010,EPI 2012,EPI 2014,EPI 2016,...,GDP PER CAPITA 2011,GDP PER CAPITA 2012,GDP PER CAPITA 2013,GDP PER CAPITA 2014,GDP PER CAPITA 2015,GDP PER CAPITA 2016,GDP PER CAPITA 2017,GDP PER CAPITA 2018,GDP PER CAPITA 2019,GDP PER CAPITA 2020
0,Albania,58.98,61.43,64.54,66.62,67.46,71.42,65.85,54.73,74.38,...,10207.73,10526.32,10570.97,11259.30,11658.87,12078.80,12770.98,13546.48,14230.99,13817.76
1,Algeria,46.81,47.51,48.17,48.93,49.79,67.41,48.56,50.08,70.28,...,13500.04,13303.33,13056.80,13003.27,12015.63,11624.34,11737.42,11921.73,11997.34,11268.26
2,Angola,42.79,43.72,45.15,47.51,48.47,36.35,47.57,28.69,51.32,...,6710.75,7412.97,7682.48,8179.30,7337.57,7103.23,7310.90,7099.97,6952.42,6538.45
3,Argentina,51.73,53.01,53.12,55.20,56.07,61.05,56.48,49.55,79.84,...,19322.23,19641.35,20131.68,19683.77,20105.20,20307.87,23597.12,23305.85,22996.99,20767.61
4,Armenia,44.61,46.23,46.64,46.65,46.46,60.44,47.48,61.67,81.60,...,8025.46,9364.38,9835.80,10036.89,9969.66,10704.23,12115.14,13020.40,14231.18,13284.16

In [33]:
# Initialize PyMongo to work with MongoDBs
conn = 'mongodb+srv://SteveD:tYzociCA7OZ1bYmu@cluster0.eouih.mongodb.net/myFirstDatabase?retryWrites=true&w=majority'
client = pymongo.MongoClient(conn)

In [48]:
# Define database and collection
ESGdb = client.Country_ESG_df

In [49]:
#Load df into a MongoDB collection
collection = ESGdb.ESG
# Insert collection
#collection.insert_many

In [ ]:
#for index, row in df.iterrows():
    #print(row['Country'], row['c2'])

In [54]:
collection.insert_many(Country_ESG_df.to_dict('records'))